const ALLOWED = new Set(["weather","rates","books","jobs","geocode"]);
function json(res,status,data){res.status(status).setHeader("Content-Type","application/json; charset=utf-8");res.setHeader("Cache-Control","public, max-age=300, s-maxage=300");return res.end(JSON.stringify(data));}
async function get(url,headers){const c=new AbortController();const t=setTimeout(()=>c.abort(),10000);try{const r=await fetch(url,{headers:headers||{},signal:c.signal});const text=await r.text();let data;try{data=JSON.parse(text)}catch{data={raw:text}}if(!r.ok)throw new Error(String(r.status));return data}finally{clearTimeout(t)}}
module.exports=async function(req,res){
if(req.method!=="GET")return json(res,405,{error:"Method not allowed"});
const type=String((req.query||{}).type||"");if(!ALLOWED.has(type))return json(res,400,{error:"Unknown tool"});
try{
if(type==="weather"){const lat=Number(req.query.lat),lon=Number(req.query.lon);if(!Number.isFinite(lat)||!Number.isFinite(lon))return json(res,400,{error:"lat/lon required"});const u="https://api.met.no/weatherapi/locationforecast/2.0/compact?lat="+encodeURIComponent(lat)+"&lon="+encodeURIComponent(lon)+"";return json(res,200,await get(u,{"User-Agent":"AI-Maroc/1.0 (https://github.com/bo9al-gif/pack-emploi-maroc)"}))}
if(type==="rates"){const base=(String(req.query.base||"EUR").toUpperCase()).replace(/[^A-Z]/g,"").slice(0,3)||"EUR";const quote=(String(req.query.quote||"MAD,USD").toUpperCase()).replace(/[^A-Z,]/g,"").slice(0,31);return json(res,200,await get("https://api.frankfurter.dev/v2/rates?base="+base+"&quotes="+quote))}
if(type==="books"){const q=String(req.query.q||"").trim().slice(0,120);if(!q)return json(res,400,{error:"q required"});return json(res,200,await get("https://openlibrary.org/search.json?q="+encodeURIComponent(q)+"&limit=8&fields=key,title,author_name,first_publish_year,cover_i",{"User-Agent":"AI-Maroc/1.0"}))}
if(type==="jobs"){const data=await get("https://www.arbeitnow.com/api/job-board-api");const items=Array.isArray(data)?data:(data.data||[]);const q=String(req.query.q||"").trim().toLowerCase().slice(0,80);const filtered=q?items.filter(j=>JSON.stringify(j).toLowerCase().includes(q)):items;return json(res,200,{data:filtered.slice(0,20),source:"Arbeitnow"})}
if(type==="geocode"){const q=String(req.query.q||"").trim().slice(0,120);if(!q)return json(res,400,{error:"q required"});return json(res,200,await get("https://nominatim.openstreetmap.org/search?format=jsonv2&limit=5&countrycodes=ma&q="+encodeURIComponent(q),{"User-Agent":"AI-Maroc/1.0"}))}
}catch(e){return json(res,502,{error:"الخدمة الخارجية ما جاوباتش دابا.",details:e.message})}}